# Generated by Django 3.2.7 on 2021-10-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211016_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_address',
            new_name='display_name',
        ),
    ]
