# Generated by Django 3.2.7 on 2021-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_email_address_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='bio', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='displayname', max_length=220),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='firstname', max_length=220),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='lastname', max_length=220),
        ),
        migrations.AlterField(
            model_name='profile',
            name='locations',
            field=models.CharField(blank=True, default='locations', max_length=220),
        ),
    ]
