# Generated by Django 3.2.7 on 2021-12-09 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventName', models.CharField(db_column='eventName', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pageName', models.ForeignKey(db_column='pageName', on_delete=django.db.models.deletion.CASCADE, to='pages.pages')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=40)),
                ('eventDescription', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pages')),
            ],
        ),
    ]
