# Generated by Django 3.2.7 on 2021-12-09 06:55

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('pageName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pageEmail', models.EmailField(max_length=254)),
                ('pageAuthor', models.CharField(blank=True, max_length=255, null=True, verbose_name=accounts.models.UserAccount)),
                ('pageDescription', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('pageName', models.ForeignKey(db_column='pageName', on_delete=django.db.models.deletion.CASCADE, to='pages.pages')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
